version = 1

exclude_patterns = [
  "ctfd/database/**",
  "ctfd/challenges/**",
  "ctfd/automation/**",
  "ctfd/assets/**",
  "ctfd/patches/**",
  "security/**",
  "tracks/**",
  "**/*.md",
  "**/*.csv",
  "**/*.sql"
]

[[analyzers]]
name = "python"
enabled = true
exclude_patterns = [
  "ctfd/database/**",
  "ctfd/challenges/**",
  "ctfd/automation/**",
  "ctfd/patches/**",
  "security/**",
  "tracks/**"
]

[[analyzers]]
name = "secrets"
enabled = true
exclude_patterns = [
  "security/**",
  "tracks/**",
  "ctfd/database/**",
  "ctfd/challenges/**",
  "ctfd/automation/**",
  "ctfd/assets/**",
  "ctfd/patches/**",
  "**/*.md",
  "**/*.csv",
  "**/*.sql"
]
