version = 1

exclude_patterns = [
  "ctfd/**",
  "security/**",
  "tracks/**",
  "**/*.md",
  "**/*.csv",
  "**/*.sql"
]

[[analyzers]]
name = "python"
enabled = true
exclude_patterns = [
  "ctfd/**",
  "security/**",
  "tracks/**"
]

[[analyzers]]
name = "secrets"
enabled = true
exclude_patterns = [
  "ctfd/**",
  "security/**",
  "tracks/**",
  "**/*.md",
  "**/*.csv",
  "**/*.sql"
]
